### PR TITLE
Feature:adding datasource for groups

### PR DESCRIPTION
**Pull request by davidferdinand**
Adding datasource to retrieve all groups

Run and tested with all results providing the correct and expected data

### CODE REVIEW

**Review by Tomy8s — APPROVED** [review]

**Comment by rocktavious** [comment]
Hello @davidferdinand - Thanks for the contribution.  Sorry for the delay here but the company has been on holiday.  We will try to look at this sometime today/tomorrow (July 5 or 6th)

**Review by matthewbrahms — CHANGES_REQUESTED** [review]
@davidferdinand Looks great, one thing we didn't call out was the need for a change entry for our release process.  We have included instructions here that should help: https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/CONTRIBUTING.md#changie-change-log-generation

Let us know when you put that in and we will get it merged!  

15JULY is our next release, and we hope to get this included in that release.

Thanks!  👍

**Comment by davidferdinand** [comment]
@matthewbrahms I have added that now.

Should I also add any docs for this? I can see the rest have some, but its not in the contributing guide

**Review by matthewbrahms — APPROVED** [review]
@davidferdinand Thanks for making the changie entry!  I added that Changie blurb to the docs for `CONTRIBUTING.md` so if you had anything else to add there, feel free!

Thanks! 👍

**Pull request merged**
