### PR TITLE
adding override feature for client timeout

### PR DESCRIPTION
**Pull request by davidferdinand**
- adding ability to set a custom value for the client timeout value in calls to GQL

This is being added due to the current continual timeout when trying to retrieve all team and service date using datasources.

### CODE REVIEW

**Review by eochoa260 — APPROVED** [review]
LGTM, thanks for the change @davidferdinand!

**Review by rocktavious — APPROVED** [review]
LGTM

**Comment by rocktavious** [comment]
@davidferdinand - we have a hackday at OpsLevel tomorrow so we probably won't release this until Monday.

**Comment by davidferdinand** [comment]
That's great. I will get ready for it next week. 

Have a great hackday!

**Comment by davidferdinand** [comment]
@rocktavious do you know when you plan to release this?

**Pull request merged**
